### ISSUE TITLE
Ubuntu 14.04 

### ISSUE THREAD

**Issue by mikerev** [sensu-plugins/sensu-pg#1]
This is incompatible with Ubuntu 14.04 while using the Sensu apt repo, as it doesn't meet the version requirement. It also needs to install debhelper, and the cleanup job in the rules file needs to go after the build otherwise it fails. 

@mrtrotl @majormoses I have a branch ready to push up if someone wants to give me rights.

**Comment by majormoses** [comment]
chatted and would accept a PR, please fork and create the PR.

**Comment by mikerev** [comment]
All set https://github.com/sensu-plugins/sensu-pg/pull/2

**Comment by mikerev** [comment]
Thanks for the work! Other than having to pass ignore_failure true due to the signature this works and can be closed.

**Comment by majormoses** [comment]
closed via #2
